const express = require("express");
const router = express.Router();
const QuizController = require("../controllers/EnglishMethodsController");
const multer = require("multer");
const storage = multer.memoryStorage();
const upload = multer({ storage });
router.post("/uploadNew",upload.single("file"),QuizController.upload);
router.get("/getQuizDetails",QuizController.getAllQuiz);
router.get("/getQuizDetails/:quizId",QuizController.getQuizDetailsById);
module.exports = router;